name: build
on: 
- pull_request
- push
- workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: setup jdk 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: checkout repository
      uses: actions/checkout@v4

    - name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: make gradle wrapper executable
      if: ${{ runner.os != 'Windows' }}
      run: chmod +x ./gradlew

    - name: build
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk17
        arguments: build
        gradle-version: wrapper

    - name: capture build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: build/libs/
